
[items]

	[items.milk_bottles]
		#If milk can be inserted into cauldrons
		"Milk Cauldron" = true
		#If milkable mobs can be milked with empty glass bottles
		"Milking with Glass Bottles" = false

[world]

	[world.generation]
		"Banana Plant generation in Beaches" = true
		"Strawberry Bush generation chance in Plains" = 12
		"Banana Plant generation in Jungles" = true
		"Mint pond generation chance in Mountains" = 6
		"Adzuki Sprouts generation chance in Forests" = 7
		"Vanilla Vine generation chance in Savannas" = 10

[mobs]

	[mobs.plantain_spider]
		"Plantain Spider spawn from Banana Bundles" = true
		"Plantain Spiders give Slipping" = true
		"Plantain Spider spawning in Jungles" = true

	[mobs.chimpanzee]
		"Chimpanzee spawning in Jungles" = true

