
#Common changes
[common]
	#Enable Maple trees.
	enableMaple = true
	#Enable Tiger trees.
	enableTiger = true
	#Enable Silverbelltrees.
	enableSilverbell = true
	#Enable Apple trees.
	enableApple = true
	#Enable Purple Heart trees.
	enablePurpleHeart = true
	#Enable Willow trees.
	enableWillow = true
	#Enable Magic trees.
	enableMagic = true

